[package]
name = "todo_app"
version = "0.1.0"
edition = "2021"

members = [
    "todo_app",
]

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4"